"""phase 9 advanced derivatives

Revision ID: 0e9178612624
Revises: cdfffe7a2ea3
Create Date: 2026-09-03 10:26:55.491774
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import infrastructure.database.types as qip

revision: str = "0e9178612624"
down_revision: str | None = "cdfffe7a2ea3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "global_surfaces",
        sa.Column("surface_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("underlying_id", sa.Uuid(), nullable=False),
        sa.Column("as_of_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("model", sa.String(length=24), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("curve_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("rho", sa.Float(), nullable=True),
        sa.Column("eta", sa.Float(), nullable=True),
        sa.Column("gamma", sa.Float(), nullable=True),
        sa.Column("n_observations", sa.Integer(), nullable=False),
        sa.Column("n_slices", sa.Integer(), nullable=False),
        sa.Column("rmse_total_variance", sa.Float(), nullable=True),
        sa.Column("weighted_rmse", sa.Float(), nullable=True),
        sa.Column("rmse_vol_points", sa.Float(), nullable=True),
        sa.Column("max_error_vol_points", sa.Float(), nullable=True),
        sa.Column("optimizer", sa.String(length=24), nullable=False),
        sa.Column("optimizer_message", sa.String(length=255), nullable=True),
        sa.Column("iterations", sa.Integer(), nullable=False),
        sa.Column("starts_attempted", sa.Integer(), nullable=False),
        sa.Column("starts_feasible", sa.Integer(), nullable=False),
        sa.Column("min_durrleman_g", sa.Float(), nullable=True),
        sa.Column("max_butterfly_quantity", sa.Float(), nullable=True),
        sa.Column("butterfly_bounds_satisfied", sa.Boolean(), nullable=False),
        sa.Column("calendar_arbitrage_free", sa.Boolean(), nullable=False),
        sa.Column("error", sa.String(length=255), nullable=True),
        sa.Column("calibration_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'CONVERGED' OR "
            "(calendar_arbitrage_free = true AND min_durrleman_g >= -1e-9)",
            name="ck_converged_global_surface_is_arbitrage_free",
        ),
        sa.CheckConstraint(
            "status <> 'CONVERGED' OR (rho IS NOT NULL AND eta IS NOT NULL AND gamma IS NOT NULL)",
            name="ck_global_surface_converged_has_parameters",
        ),
        sa.ForeignKeyConstraint(["analysis_id"], ["chain_analyses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["underlying_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("global_surfaces", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_global_surfaces_surface_id"), ["surface_id"], unique=False
        )
        batch_op.create_index(
            "ix_global_surfaces_underlying", ["underlying_id", "as_of_timestamp"], unique=False
        )
        batch_op.create_index("ix_global_surfaces_user", ["user_id", "created_at"], unique=False)

    op.create_table(
        "heston_calibrations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("underlying_id", sa.Uuid(), nullable=False),
        sa.Column("as_of_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("v0", sa.Float(), nullable=True),
        sa.Column("kappa", sa.Float(), nullable=True),
        sa.Column("theta", sa.Float(), nullable=True),
        sa.Column("xi", sa.Float(), nullable=True),
        sa.Column("rho", sa.Float(), nullable=True),
        sa.Column("n_observations", sa.Integer(), nullable=False),
        sa.Column("n_maturities", sa.Integer(), nullable=False),
        sa.Column("rmse_price", sa.Float(), nullable=True),
        sa.Column("rmse_vol_points", sa.Float(), nullable=True),
        sa.Column("max_error_vol_points", sa.Float(), nullable=True),
        sa.Column("optimizer", sa.String(length=24), nullable=False),
        sa.Column("optimizer_message", sa.String(length=255), nullable=True),
        sa.Column("iterations", sa.Integer(), nullable=False),
        sa.Column("starts_attempted", sa.Integer(), nullable=False),
        sa.Column("starts_feasible", sa.Integer(), nullable=False),
        sa.Column("feller", sa.Float(), nullable=True),
        sa.Column("satisfies_feller", sa.Boolean(), nullable=False),
        sa.Column("feller_enforced", sa.Boolean(), nullable=False),
        sa.Column("warnings", qip.JSONDict(), nullable=False),
        sa.Column("error", sa.String(length=255), nullable=True),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'CONVERGED' OR (v0 IS NOT NULL AND kappa IS NOT NULL "
            "AND theta IS NOT NULL AND xi IS NOT NULL AND rho IS NOT NULL)",
            name="ck_heston_converged_has_parameters",
        ),
        sa.CheckConstraint(
            "feller_enforced = false OR feller >= -1e-9",
            name="ck_heston_enforced_feller_is_satisfied",
        ),
        sa.ForeignKeyConstraint(["analysis_id"], ["chain_analyses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["underlying_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("heston_calibrations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_heston_underlying", ["user_id", "underlying_id", "as_of_timestamp"], unique=False
        )

    op.create_table(
        "global_surface_slices",
        sa.Column("global_surface_id", sa.Uuid(), nullable=False),
        sa.Column("expiry", sa.Date(), nullable=False),
        sa.Column("time_to_expiry", sa.Float(), nullable=False),
        sa.Column("forward", sa.Float(), nullable=False),
        sa.Column("discount_factor", sa.Float(), nullable=False),
        sa.Column("forward_method", sa.String(length=24), nullable=True),
        sa.Column("forward_confidence", sa.Float(), nullable=False),
        sa.Column("theta", sa.Float(), nullable=False),
        sa.Column("atm_volatility", sa.Float(), nullable=False),
        sa.Column("n_observations", sa.Integer(), nullable=False),
        sa.Column("rmse_vol_points", sa.Float(), nullable=True),
        sa.Column("max_error_vol_points", sa.Float(), nullable=True),
        sa.Column("k_min", sa.Float(), nullable=True),
        sa.Column("k_max", sa.Float(), nullable=True),
        sa.Column("butterfly_first", sa.Float(), nullable=True),
        sa.Column("butterfly_second", sa.Float(), nullable=True),
        sa.Column("butterfly_bounds_satisfied", sa.Boolean(), nullable=False),
        sa.Column("min_durrleman_g", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("theta > 0", name="ck_global_surface_slice_theta_positive"),
        sa.ForeignKeyConstraint(["global_surface_id"], ["global_surfaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("global_surface_id", "expiry", name="uq_global_surface_slice_expiry"),
    )
    with op.batch_alter_table("global_surface_slices", schema=None) as batch_op:
        batch_op.create_index(
            "ix_global_surface_slices_surface", ["global_surface_id", "expiry"], unique=False
        )

    op.create_table(
        "local_volatility_surfaces",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("global_surface_id", sa.Uuid(), nullable=False),
        sa.Column("underlying_id", sa.Uuid(), nullable=False),
        sa.Column("as_of_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("spot", sa.Float(), nullable=False),
        sa.Column("carry", sa.Float(), nullable=False),
        sa.Column("total_points", sa.Integer(), nullable=False),
        sa.Column("valid_points", sa.Integer(), nullable=False),
        sa.Column("flagged_points", sa.Integer(), nullable=False),
        sa.Column("coverage", sa.Float(), nullable=False),
        sa.Column("flag_counts", qip.JSONDict(), nullable=False),
        sa.Column("grid", qip.JSONDict(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "coverage >= 0 AND coverage <= 1", name="ck_local_vol_coverage_fraction"
        ),
        sa.CheckConstraint(
            "total_points = valid_points + flagged_points",
            name="ck_local_vol_grid_conserves_points",
        ),
        sa.ForeignKeyConstraint(["global_surface_id"], ["global_surfaces.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["underlying_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("local_volatility_surfaces", schema=None) as batch_op:
        batch_op.create_index("ix_local_vol_surfaces_global", ["global_surface_id"], unique=False)
        batch_op.create_index("ix_local_vol_surfaces_user", ["user_id", "created_at"], unique=False)

    op.create_table(
        "model_consensus_runs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("global_surface_id", sa.Uuid(), nullable=True),
        sa.Column("heston_calibration_id", sa.Uuid(), nullable=True),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("underlying_id", sa.Uuid(), nullable=False),
        sa.Column("as_of_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("expiry", sa.Date(), nullable=False),
        sa.Column("strike", qip.DecimalType(), nullable=False),
        sa.Column("option_type", sa.String(length=8), nullable=False),
        sa.Column("spot", sa.Float(), nullable=False),
        sa.Column("time_to_expiry", sa.Float(), nullable=False),
        sa.Column("risk_free_rate", sa.Float(), nullable=False),
        sa.Column("dividend_yield", sa.Float(), nullable=False),
        sa.Column("reference_volatility", sa.Float(), nullable=True),
        sa.Column("models_requested", sa.Integer(), nullable=False),
        sa.Column("models_available", sa.Integer(), nullable=False),
        sa.Column("reference_value", sa.Float(), nullable=True),
        sa.Column("reference_low", sa.Float(), nullable=True),
        sa.Column("reference_high", sa.Float(), nullable=True),
        sa.Column("dispersion_absolute", sa.Float(), nullable=True),
        sa.Column("dispersion_relative", sa.Float(), nullable=True),
        sa.Column("standard_deviation", sa.Float(), nullable=True),
        sa.Column("market_price", sa.Float(), nullable=True),
        sa.Column("market_deviation", sa.Float(), nullable=True),
        sa.Column("market_deviation_relative", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("confidence_contributions", qip.JSONDict(), nullable=False),
        sa.Column("vanna", sa.Float(), nullable=True),
        sa.Column("volga", sa.Float(), nullable=True),
        sa.Column("charm_per_day", sa.Float(), nullable=True),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("paths", sa.Integer(), nullable=False),
        sa.Column("grid", qip.JSONDict(), nullable=False),
        sa.Column("warnings", qip.JSONDict(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(reference_value IS NULL AND models_available = 0) OR "
            "(reference_value IS NOT NULL AND models_available > 0)",
            name="ck_consensus_value_requires_a_model",
        ),
        sa.CheckConstraint(
            "models_available <= models_requested", name="ck_consensus_available_le_requested"
        ),
        sa.CheckConstraint(
            "reference_value IS NULL OR "
            "(reference_value >= reference_low AND reference_value <= reference_high)",
            name="ck_consensus_reference_is_bracketed",
        ),
        sa.ForeignKeyConstraint(["global_surface_id"], ["global_surfaces.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["heston_calibration_id"], ["heston_calibrations.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["underlying_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("model_consensus_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_consensus_instrument", ["instrument_id", "as_of_timestamp"], unique=False
        )
        batch_op.create_index("ix_consensus_user", ["user_id", "created_at"], unique=False)

    op.create_table(
        "risk_neutral_densities",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("global_surface_id", sa.Uuid(), nullable=False),
        sa.Column("underlying_id", sa.Uuid(), nullable=False),
        sa.Column("expiry", sa.Date(), nullable=False),
        sa.Column("time_to_expiry", sa.Float(), nullable=False),
        sa.Column("forward", sa.Float(), nullable=False),
        sa.Column("discount_factor", sa.Float(), nullable=False),
        sa.Column("total_mass", sa.Float(), nullable=False),
        sa.Column("implied_mean", sa.Float(), nullable=False),
        sa.Column("negative_mass", sa.Float(), nullable=False),
        sa.Column("mean_error", sa.Float(), nullable=False),
        sa.Column("is_admissible", sa.Boolean(), nullable=False),
        sa.Column("flags", qip.JSONDict(), nullable=False),
        sa.Column("percentile_5", sa.Float(), nullable=True),
        sa.Column("percentile_25", sa.Float(), nullable=True),
        sa.Column("percentile_50", sa.Float(), nullable=True),
        sa.Column("percentile_75", sa.Float(), nullable=True),
        sa.Column("percentile_95", sa.Float(), nullable=True),
        sa.Column("strikes", qip.JSONDict(), nullable=False),
        sa.Column("density", qip.JSONDict(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "is_admissible = true OR (percentile_5 IS NULL AND percentile_25 IS NULL "
            "AND percentile_50 IS NULL AND percentile_75 IS NULL "
            "AND percentile_95 IS NULL)",
            name="ck_density_quantiles_require_admissibility",
        ),
        sa.ForeignKeyConstraint(["global_surface_id"], ["global_surfaces.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["underlying_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("global_surface_id", "expiry", name="uq_density_surface_expiry"),
    )
    with op.batch_alter_table("risk_neutral_densities", schema=None) as batch_op:
        batch_op.create_index("ix_densities_surface", ["global_surface_id", "expiry"], unique=False)

    op.create_table(
        "model_values",
        sa.Column("consensus_id", sa.Uuid(), nullable=False),
        sa.Column("model", sa.String(length=32), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("method", sa.String(length=128), nullable=False),
        sa.Column("inputs_used", qip.JSONDict(), nullable=False),
        sa.Column("diagnostics", qip.JSONDict(), nullable=False),
        sa.Column("warnings", qip.JSONDict(), nullable=False),
        sa.Column("unavailable_reason", sa.String(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(value IS NOT NULL AND unavailable_reason IS NULL) OR "
            "(value IS NULL AND unavailable_reason IS NOT NULL)",
            name="ck_model_value_has_value_or_reason",
        ),
        sa.ForeignKeyConstraint(["consensus_id"], ["model_consensus_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("consensus_id", "model", name="uq_consensus_model"),
    )
    with op.batch_alter_table("model_values", schema=None) as batch_op:
        batch_op.create_index("ix_model_values_consensus", ["consensus_id", "model"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("model_values", schema=None) as batch_op:
        batch_op.drop_index("ix_model_values_consensus")

    op.drop_table("model_values")
    with op.batch_alter_table("risk_neutral_densities", schema=None) as batch_op:
        batch_op.drop_index("ix_densities_surface")

    op.drop_table("risk_neutral_densities")
    with op.batch_alter_table("model_consensus_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_consensus_user")
        batch_op.drop_index("ix_consensus_instrument")

    op.drop_table("model_consensus_runs")
    with op.batch_alter_table("local_volatility_surfaces", schema=None) as batch_op:
        batch_op.drop_index("ix_local_vol_surfaces_user")
        batch_op.drop_index("ix_local_vol_surfaces_global")

    op.drop_table("local_volatility_surfaces")
    with op.batch_alter_table("global_surface_slices", schema=None) as batch_op:
        batch_op.drop_index("ix_global_surface_slices_surface")

    op.drop_table("global_surface_slices")
    with op.batch_alter_table("heston_calibrations", schema=None) as batch_op:
        batch_op.drop_index("ix_heston_underlying")

    op.drop_table("heston_calibrations")
    with op.batch_alter_table("global_surfaces", schema=None) as batch_op:
        batch_op.drop_index("ix_global_surfaces_user")
        batch_op.drop_index("ix_global_surfaces_underlying")
        batch_op.drop_index(batch_op.f("ix_global_surfaces_surface_id"))

    op.drop_table("global_surfaces")
    # ### end Alembic commands ###
