"""phase 10 microstructure

Revision ID: 62f6ffc9ba6a
Revises: 0e9178612624
Create Date: 2026-09-03 12:24:09.343590
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import infrastructure.database.types as qip

revision: str = "62f6ffc9ba6a"
down_revision: str | None = "0e9178612624"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "microstructure_datasets",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("snapshot_upload_id", sa.Uuid(), nullable=True),
        sa.Column("event_upload_id", sa.Uuid(), nullable=True),
        sa.Column("snapshot_key", sa.String(length=512), nullable=True),
        sa.Column("event_key", sa.String(length=512), nullable=True),
        sa.Column("rejection_key", sa.String(length=512), nullable=True),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("dataset_digest", sa.String(length=64), nullable=True),
        sa.Column("snapshot_rows_in", sa.Integer(), nullable=False),
        sa.Column("snapshot_rows_kept", sa.Integer(), nullable=False),
        sa.Column("snapshot_rows_rejected", sa.Integer(), nullable=False),
        sa.Column("event_rows_in", sa.Integer(), nullable=False),
        sa.Column("event_rows_kept", sa.Integer(), nullable=False),
        sa.Column("event_rows_rejected", sa.Integer(), nullable=False),
        sa.Column("rejection_counts", qip.JSONDict(), nullable=False),
        sa.Column("first_timestamp", qip.UTCDateTime(), nullable=True),
        sa.Column("last_timestamp", qip.UTCDateTime(), nullable=True),
        sa.Column("span_seconds", sa.Float(), nullable=False),
        sa.Column("max_depth_levels", sa.Integer(), nullable=False),
        sa.Column("availability", qip.JSONDict(), nullable=False),
        sa.Column("available_capabilities", qip.JSONDict(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "event_rows_in = event_rows_kept + event_rows_rejected",
            name="ck_dataset_conserves_event_rows",
        ),
        sa.CheckConstraint(
            "snapshot_key IS NOT NULL OR event_key IS NOT NULL", name="ck_dataset_holds_something"
        ),
        sa.CheckConstraint(
            "snapshot_rows_in = snapshot_rows_kept + snapshot_rows_rejected",
            name="ck_dataset_conserves_snapshot_rows",
        ),
        sa.CheckConstraint("span_seconds >= 0", name="ck_dataset_span_non_negative"),
        sa.ForeignKeyConstraint(["event_upload_id"], ["uploads.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["snapshot_upload_id"], ["uploads.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("microstructure_datasets", schema=None) as batch_op:
        batch_op.create_index(
            "ix_microstructure_datasets_instrument",
            ["instrument_id", "first_timestamp"],
            unique=False,
        )
        batch_op.create_index(
            "ix_microstructure_datasets_user", ["user_id", "created_at"], unique=False
        )

    op.create_table(
        "book_analytics_reports",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("levels", sa.Integer(), nullable=False),
        sa.Column("weighted_decay", sa.Float(), nullable=False),
        sa.Column("snapshots_analysed", sa.Integer(), nullable=False),
        sa.Column("window_start", qip.UTCDateTime(), nullable=True),
        sa.Column("window_end", qip.UTCDateTime(), nullable=True),
        sa.Column("crossed_snapshots", sa.Integer(), nullable=False),
        sa.Column("locked_snapshots", sa.Integer(), nullable=False),
        sa.Column("median_spread", sa.Float(), nullable=True),
        sa.Column("median_relative_spread", sa.Float(), nullable=True),
        sa.Column("median_imbalance", sa.Float(), nullable=True),
        sa.Column("median_microprice_tilt", sa.Float(), nullable=True),
        sa.Column("measures", qip.JSONDict(), nullable=False),
        sa.Column("trade_costs", qip.JSONDict(), nullable=False),
        sa.Column("preview_series", qip.JSONDict(), nullable=False),
        sa.Column("series_key", sa.String(length=512), nullable=True),
        sa.Column("warnings", qip.JSONDict(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("levels >= 1", name="ck_book_report_levels_positive"),
        sa.CheckConstraint("snapshots_analysed >= 0", name="ck_book_report_snapshots_non_negative"),
        sa.CheckConstraint("weighted_decay >= 0", name="ck_book_report_decay_non_negative"),
        sa.ForeignKeyConstraint(["dataset_id"], ["microstructure_datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("book_analytics_reports", schema=None) as batch_op:
        batch_op.create_index("ix_book_reports_dataset", ["dataset_id", "created_at"], unique=False)
        batch_op.create_index("ix_book_reports_user", ["user_id", "created_at"], unique=False)

    op.create_table(
        "intensity_models",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=200), nullable=False),
        sa.Column("event_types", qip.JSONDict(), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=True),
        sa.Column("price", qip.DecimalType(), nullable=True),
        sa.Column("events_selected", sa.Integer(), nullable=False),
        sa.Column("window_start", qip.UTCDateTime(), nullable=False),
        sa.Column("window_end", qip.UTCDateTime(), nullable=False),
        sa.Column("split_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("train_fraction", sa.Float(), nullable=False),
        sa.Column("poisson_rate", sa.Float(), nullable=False),
        sa.Column("poisson_train_log_likelihood", sa.Float(), nullable=False),
        sa.Column("poisson_held_out_log_likelihood", sa.Float(), nullable=False),
        sa.Column("hawkes_mu", sa.Float(), nullable=True),
        sa.Column("hawkes_alpha", sa.Float(), nullable=True),
        sa.Column("hawkes_beta", sa.Float(), nullable=True),
        sa.Column("hawkes_branching_ratio", sa.Float(), nullable=True),
        sa.Column("hawkes_train_log_likelihood", sa.Float(), nullable=True),
        sa.Column("hawkes_held_out_log_likelihood", sa.Float(), nullable=True),
        sa.Column("hawkes_converged", sa.Boolean(), nullable=False),
        sa.Column("held_out_events", sa.Integer(), nullable=False),
        sa.Column("mean_gain_per_event", sa.Float(), nullable=True),
        sa.Column("test_statistic", sa.Float(), nullable=True),
        sa.Column("critical_value", sa.Float(), nullable=False),
        sa.Column("hawkes_is_adopted", sa.Boolean(), nullable=False),
        sa.Column("adopted_model", sa.String(length=32), nullable=False),
        sa.Column("adopted_rate", sa.Float(), nullable=False),
        sa.Column("verdict_reason", sa.String(length=1000), nullable=False),
        sa.Column("comparison", qip.JSONDict(), nullable=False),
        sa.Column("warnings", qip.JSONDict(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(adopted_model = 'HAWKES_EXPONENTIAL') = hawkes_is_adopted",
            name="ck_intensity_adopted_model_matches_the_verdict",
        ),
        sa.CheckConstraint(
            "NOT hawkes_is_adopted OR ("
            "  test_statistic IS NOT NULL"
            "  AND test_statistic > critical_value"
            "  AND hawkes_converged"
            "  AND hawkes_branching_ratio IS NOT NULL"
            "  AND hawkes_branching_ratio < 1)",
            name="ck_intensity_hawkes_needs_a_held_out_win",
        ),
        sa.CheckConstraint("poisson_rate >= 0", name="ck_intensity_rate_non_negative"),
        sa.CheckConstraint(
            "split_timestamp > window_start AND split_timestamp < window_end",
            name="ck_intensity_split_inside_window",
        ),
        sa.CheckConstraint("window_end > window_start", name="ck_intensity_window_ordered"),
        sa.ForeignKeyConstraint(["dataset_id"], ["microstructure_datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("intensity_models", schema=None) as batch_op:
        batch_op.create_index(
            "ix_intensity_models_dataset", ["dataset_id", "created_at"], unique=False
        )
        batch_op.create_index("ix_intensity_models_user", ["user_id", "created_at"], unique=False)

    op.create_table(
        "queue_estimates",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("dataset_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("price", qip.DecimalType(), nullable=False),
        sa.Column("snapshot_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("quantity_ahead", qip.DecimalType(), nullable=False),
        sa.Column("level_quantity", qip.DecimalType(), nullable=False),
        sa.Column("horizon_seconds", sa.Float(), nullable=False),
        sa.Column("observation_window_seconds", sa.Float(), nullable=False),
        sa.Column("trades_observed", sa.Integer(), nullable=False),
        sa.Column("cancels_observed", sa.Integer(), nullable=False),
        sa.Column("pessimistic_fill_probability", sa.Float(), nullable=False),
        sa.Column("pessimistic_wait_seconds", sa.Float(), nullable=True),
        sa.Column("optimistic_fill_probability", sa.Float(), nullable=False),
        sa.Column("optimistic_wait_seconds", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("assumptions", qip.JSONDict(), nullable=False),
        sa.Column("detail", qip.JSONDict(), nullable=False),
        sa.Column("warnings", qip.JSONDict(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_queue_confidence_is_a_score"
        ),
        sa.CheckConstraint("horizon_seconds > 0", name="ck_queue_horizon_positive"),
        sa.CheckConstraint(
            "optimistic_fill_probability >= pessimistic_fill_probability",
            name="ck_queue_estimate_is_a_bracket",
        ),
        sa.CheckConstraint(
            "pessimistic_fill_probability >= 0 AND pessimistic_fill_probability <= 1"
            " AND optimistic_fill_probability >= 0 AND optimistic_fill_probability <= 1",
            name="ck_queue_probabilities_are_probabilities",
        ),
        sa.CheckConstraint("quantity_ahead >= 0", name="ck_queue_quantity_ahead_non_negative"),
        sa.CheckConstraint(
            "trades_observed + cancels_observed > 0", name="ck_queue_needs_an_observed_departure"
        ),
        sa.ForeignKeyConstraint(["dataset_id"], ["microstructure_datasets.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("queue_estimates", schema=None) as batch_op:
        batch_op.create_index(
            "ix_queue_estimates_dataset", ["dataset_id", "created_at"], unique=False
        )
        batch_op.create_index("ix_queue_estimates_user", ["user_id", "created_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("queue_estimates", schema=None) as batch_op:
        batch_op.drop_index("ix_queue_estimates_user")
        batch_op.drop_index("ix_queue_estimates_dataset")

    op.drop_table("queue_estimates")
    with op.batch_alter_table("intensity_models", schema=None) as batch_op:
        batch_op.drop_index("ix_intensity_models_user")
        batch_op.drop_index("ix_intensity_models_dataset")

    op.drop_table("intensity_models")
    with op.batch_alter_table("book_analytics_reports", schema=None) as batch_op:
        batch_op.drop_index("ix_book_reports_user")
        batch_op.drop_index("ix_book_reports_dataset")

    op.drop_table("book_analytics_reports")
    with op.batch_alter_table("microstructure_datasets", schema=None) as batch_op:
        batch_op.drop_index("ix_microstructure_datasets_user")
        batch_op.drop_index("ix_microstructure_datasets_instrument")

    op.drop_table("microstructure_datasets")
    # ### end Alembic commands ###
