"""phase 1 derivatives

Revision ID: 7b9c71f2609c
Revises: 0002_timescale
Create Date: 2026-09-01 16:56:53.759946
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import infrastructure.database.types as qip

revision: str = "7b9c71f2609c"
down_revision: str | None = "0002_timescale"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "yield_curves",
        sa.Column("curve_id", sa.String(length=64), nullable=False),
        sa.Column("as_of_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("day_count", sa.String(length=16), nullable=False),
        sa.Column("interpolation", sa.String(length=24), nullable=False),
        sa.Column("label", sa.String(length=64), nullable=True),
        sa.Column("points", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("curve_id"),
    )
    with op.batch_alter_table("yield_curves", schema=None) as batch_op:
        batch_op.create_index(
            "ix_yield_curves_lookup", ["currency", "as_of_timestamp"], unique=False
        )

    op.create_table(
        "chain_analyses",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("chain_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("underlying_id", sa.Uuid(), nullable=False),
        sa.Column("as_of_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("curve_id", sa.String(length=64), nullable=True),
        sa.Column("day_count", sa.String(length=16), nullable=False),
        sa.Column("settlement_time_utc", sa.String(length=16), nullable=True),
        sa.Column("underlying_price", qip.DecimalType(), nullable=True),
        sa.Column("quotes_in", sa.Integer(), nullable=False),
        sa.Column("quotes_solved", sa.Integer(), nullable=False),
        sa.Column("expiries", sa.Integer(), nullable=False),
        sa.Column("summary", qip.JSONDict(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("quotes_solved <= quotes_in", name="ck_analysis_solved_le_in"),
        sa.ForeignKeyConstraint(
            ["chain_snapshot_id"], ["option_chain_snapshots.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["underlying_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("chain_analyses", schema=None) as batch_op:
        batch_op.create_index(
            "ix_chain_analyses_snapshot", ["chain_snapshot_id", "created_at"], unique=False
        )
        batch_op.create_index("ix_chain_analyses_user", ["user_id", "created_at"], unique=False)

    op.create_table(
        "forward_estimates",
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("underlying_id", sa.Uuid(), nullable=False),
        sa.Column("expiry", sa.Date(), nullable=False),
        sa.Column("method", sa.String(length=24), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("observations", sa.Integer(), nullable=False),
        sa.Column("residual_error", sa.Float(), nullable=True),
        sa.Column("discount_factor", sa.Float(), nullable=True),
        sa.Column("time_to_expiry", sa.Float(), nullable=True),
        sa.Column("error", sa.String(length=32), nullable=True),
        sa.Column("assumptions", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["analysis_id"], ["chain_analyses.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("analysis_id", "expiry", "method", name="uq_forward_per_method"),
    )
    with op.batch_alter_table("forward_estimates", schema=None) as batch_op:
        batch_op.create_index(
            "ix_forward_estimates_analysis", ["analysis_id", "expiry"], unique=False
        )

    op.create_table(
        "option_implied_vols",
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("expiry", sa.Date(), nullable=False),
        sa.Column("strike", qip.DecimalType(), nullable=False),
        sa.Column("option_type", sa.String(length=8), nullable=False),
        sa.Column("price_used", sa.Float(), nullable=True),
        sa.Column("price_source", sa.String(length=8), nullable=False),
        sa.Column("market_iv", sa.Float(), nullable=True),
        sa.Column("market_iv_bid", sa.Float(), nullable=True),
        sa.Column("market_iv_ask", sa.Float(), nullable=True),
        sa.Column("converged", sa.Boolean(), nullable=False),
        sa.Column("iterations", sa.Integer(), nullable=False),
        sa.Column("solver", sa.String(length=32), nullable=False),
        sa.Column("error", sa.String(length=32), nullable=True),
        sa.Column("vega", sa.Float(), nullable=True),
        sa.Column("uncertainty", sa.Float(), nullable=True),
        sa.Column("time_to_expiry", sa.Float(), nullable=True),
        sa.Column("log_moneyness", sa.Float(), nullable=True),
        sa.Column("total_variance", sa.Float(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("used_for_smile", sa.Boolean(), nullable=False),
        sa.Column("smile_exclusion", sa.String(length=32), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "market_iv IS NOT NULL OR error IS NOT NULL", name="ck_implied_vol_has_value_or_reason"
        ),
        sa.ForeignKeyConstraint(["analysis_id"], ["chain_analyses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("option_implied_vols", schema=None) as batch_op:
        batch_op.create_index(
            "ix_implied_vols_analysis",
            ["analysis_id", "expiry", "strike", "option_type"],
            unique=False,
        )
        batch_op.create_index("ix_implied_vols_instrument", ["instrument_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("option_implied_vols", schema=None) as batch_op:
        batch_op.drop_index("ix_implied_vols_instrument")
        batch_op.drop_index("ix_implied_vols_analysis")

    op.drop_table("option_implied_vols")
    with op.batch_alter_table("forward_estimates", schema=None) as batch_op:
        batch_op.drop_index("ix_forward_estimates_analysis")

    op.drop_table("forward_estimates")
    with op.batch_alter_table("chain_analyses", schema=None) as batch_op:
        batch_op.drop_index("ix_chain_analyses_user")
        batch_op.drop_index("ix_chain_analyses_snapshot")

    op.drop_table("chain_analyses")
    with op.batch_alter_table("yield_curves", schema=None) as batch_op:
        batch_op.drop_index("ix_yield_curves_lookup")

    op.drop_table("yield_curves")
    # ### end Alembic commands ###
