"""phase 7 execution

Revision ID: 7fe8f4fa4533
Revises: 7fedfdce19b2
Create Date: 2026-09-02 17:03:43.964124
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import infrastructure.database.types as qip

revision: str = "7fe8f4fa4533"
down_revision: str | None = "7fedfdce19b2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execution_reports",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("parent_order_key", sa.String(length=200), nullable=False),
        sa.Column("grouping_method", sa.String(length=24), nullable=False),
        sa.Column("grouping_is_inferred", sa.Boolean(), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("canonical_key", sa.String(length=200), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("multiplier", qip.DecimalType(), nullable=False),
        sa.Column("fills", sa.Integer(), nullable=False),
        sa.Column("filled_quantity", qip.DecimalType(), nullable=False),
        sa.Column("order_quantity", qip.DecimalType(), nullable=True),
        sa.Column("average_price", qip.DecimalType(), nullable=False),
        sa.Column("fees", qip.DecimalType(), nullable=False),
        sa.Column("window_start", qip.UTCDateTime(), nullable=False),
        sa.Column("window_end", qip.UTCDateTime(), nullable=False),
        sa.Column("primary_benchmark", sa.String(length=24), nullable=False),
        sa.Column("primary_benchmark_price", qip.DecimalType(), nullable=True),
        sa.Column("shortfall_currency", sa.Float(), nullable=True),
        sa.Column("shortfall_bps", sa.Float(), nullable=True),
        sa.Column("shortfall_percent", sa.Float(), nullable=True),
        sa.Column("observations", sa.Integer(), nullable=False),
        sa.Column("coverage_span_ratio", sa.Float(), nullable=False),
        sa.Column("coverage_is_sufficient", sa.Boolean(), nullable=False),
        sa.Column("benchmarks", qip.JSONDict(), nullable=False),
        sa.Column("shortfalls", qip.JSONDict(), nullable=False),
        sa.Column("unavailable_shortfalls", qip.JSONDict(), nullable=False),
        sa.Column("decomposition", qip.JSONDict(), nullable=True),
        sa.Column("market_window", qip.JSONDict(), nullable=False),
        sa.Column("warnings", qip.JSONDict(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(primary_benchmark_price IS NULL) = (shortfall_currency IS NULL)",
            name="ck_report_shortfall_needs_benchmark",
        ),
        sa.CheckConstraint("filled_quantity > 0", name="ck_report_filled_quantity_positive"),
        sa.CheckConstraint("window_end >= window_start", name="ck_report_window_ordered"),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("execution_reports", schema=None) as batch_op:
        batch_op.create_index(
            "ix_execution_reports_parent", ["user_id", "parent_order_key"], unique=False
        )
        batch_op.create_index("ix_execution_reports_user", ["user_id", "created_at"], unique=False)

    op.create_table(
        "executions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("upload_id", sa.Uuid(), nullable=True),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("quantity", qip.DecimalType(), nullable=False),
        sa.Column("execution_price", qip.DecimalType(), nullable=False),
        sa.Column("exchange_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("receive_timestamp", qip.UTCDateTime(), nullable=True),
        sa.Column("order_id", sa.String(length=128), nullable=True),
        sa.Column("parent_order_key", sa.String(length=128), nullable=True),
        sa.Column("order_type", sa.String(length=16), nullable=False),
        sa.Column("limit_price", qip.DecimalType(), nullable=True),
        sa.Column("order_quantity", qip.DecimalType(), nullable=True),
        sa.Column("submit_timestamp", qip.UTCDateTime(), nullable=True),
        sa.Column("decision_timestamp", qip.UTCDateTime(), nullable=True),
        sa.Column("broker", sa.String(length=64), nullable=True),
        sa.Column("venue", sa.String(length=32), nullable=True),
        sa.Column("fees", qip.DecimalType(), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("execution_metadata", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("execution_price >= 0", name="ck_execution_price_non_negative"),
        sa.CheckConstraint("fees >= 0", name="ck_execution_fees_non_negative"),
        sa.CheckConstraint("quantity > 0", name="ck_execution_quantity_positive"),
        sa.CheckConstraint(
            "submit_timestamp IS NULL OR submit_timestamp <= exchange_timestamp",
            name="ck_execution_submit_not_after_fill",
        ),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["upload_id"], ["uploads.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_executions_instrument_time", ["instrument_id", "exchange_timestamp"], unique=False
        )
        batch_op.create_index("ix_executions_parent", ["user_id", "parent_order_key"], unique=False)
        batch_op.create_index(
            "ix_executions_user_time", ["user_id", "exchange_timestamp"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("executions", schema=None) as batch_op:
        batch_op.drop_index("ix_executions_user_time")
        batch_op.drop_index("ix_executions_parent")
        batch_op.drop_index("ix_executions_instrument_time")

    op.drop_table("executions")
    with op.batch_alter_table("execution_reports", schema=None) as batch_op:
        batch_op.drop_index("ix_execution_reports_user")
        batch_op.drop_index("ix_execution_reports_parent")

    op.drop_table("execution_reports")
    # ### end Alembic commands ###
