"""phase 6 margin

Revision ID: 7fedfdce19b2
Revises: df6172d6f160
Create Date: 2026-09-02 16:07:29.051388
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import infrastructure.database.types as qip

revision: str = "7fedfdce19b2"
down_revision: str | None = "df6172d6f160"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "margin_results",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=24), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("estimated_margin", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("eligible_capital", sa.Float(), nullable=True),
        sa.Column("buffer", sa.Float(), nullable=True),
        sa.Column("utilisation", sa.Float(), nullable=True),
        sa.Column("in_shortfall_at_rest", sa.Boolean(), nullable=False),
        sa.Column("vol_co_shock", sa.Float(), nullable=False),
        sa.Column("worst_spot_return", sa.Float(), nullable=False),
        sa.Column("worst_vol_points", sa.Float(), nullable=False),
        sa.Column("worst_loss", sa.Float(), nullable=False),
        sa.Column("worst_at_grid_edge", sa.Boolean(), nullable=False),
        sa.Column("positions", sa.Integer(), nullable=False),
        sa.Column("excluded_positions", sa.Integer(), nullable=False),
        sa.Column("summary", sa.String(length=1000), nullable=False),
        sa.Column("components", qip.JSONDict(), nullable=False),
        sa.Column("assumptions", qip.JSONDict(), nullable=False),
        sa.Column("parameters", qip.JSONDict(), nullable=False),
        sa.Column("shortfall_region", qip.JSONDict(), nullable=False),
        sa.Column("ladder", qip.JSONDict(), nullable=False),
        sa.Column("warnings", qip.JSONDict(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_margin_confidence_in_range"
        ),
        sa.CheckConstraint(
            "eligible_capital IS NOT NULL OR (buffer IS NULL AND utilisation IS NULL)",
            name="ck_margin_buffer_requires_capital",
        ),
        sa.CheckConstraint("estimated_margin >= 0", name="ck_margin_estimate_non_negative"),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["risk_snapshots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("margin_results", schema=None) as batch_op:
        batch_op.create_index(
            "ix_margin_results_portfolio", ["portfolio_id", "created_at"], unique=False
        )
        batch_op.create_index("ix_margin_results_snapshot", ["snapshot_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("margin_results", schema=None) as batch_op:
        batch_op.drop_index("ix_margin_results_snapshot")
        batch_op.drop_index("ix_margin_results_portfolio")

    op.drop_table("margin_results")
    # ### end Alembic commands ###
