"""phase 11 unified order analysis

Revision ID: 9edd21fa707a
Revises: 62f6ffc9ba6a
Create Date: 2026-09-03 13:57:36.471845
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import infrastructure.database.types as qip

revision: str = "9edd21fa707a"
down_revision: str | None = "62f6ffc9ba6a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_analyses",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("quantity", qip.DecimalType(), nullable=False),
        sa.Column("order_type", sa.String(length=16), nullable=False),
        sa.Column("limit_price", qip.DecimalType(), nullable=True),
        sa.Column("as_of_timestamp", qip.UTCDateTime(), nullable=True),
        sa.Column("market_state_id", sa.String(length=64), nullable=True),
        sa.Column("base_currency", sa.String(length=3), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("branches_ok", sa.Integer(), nullable=False),
        sa.Column("branches_failed", sa.Integer(), nullable=False),
        sa.Column("branch_status", qip.JSONDict(), nullable=False),
        sa.Column("results", qip.JSONDict(), nullable=False),
        sa.Column("warnings", qip.JSONDict(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'OK' AND branches_failed = 0 AND branches_ok > 0) "
            "OR (status = 'PARTIAL' AND branches_failed > 0 AND branches_ok > 0) "
            "OR (status = 'FAILED' AND branches_ok = 0)",
            name="ck_order_analysis_status_matches_its_branches",
        ),
        sa.CheckConstraint(
            "status = 'FAILED' OR market_state_id IS NOT NULL",
            name="ck_order_analysis_names_its_market_state",
        ),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("order_analyses", schema=None) as batch_op:
        batch_op.create_index(
            "ix_order_analyses_portfolio", ["portfolio_id", "created_at"], unique=False
        )
        batch_op.create_index("ix_order_analyses_user", ["user_id", "created_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_analyses", schema=None) as batch_op:
        batch_op.drop_index("ix_order_analyses_user")
        batch_op.drop_index("ix_order_analyses_portfolio")

    op.drop_table("order_analyses")
    # ### end Alembic commands ###
