"""phase 2 volatility surface

Revision ID: a3246f652ccf
Revises: 7b9c71f2609c
Create Date: 2026-09-01 17:51:17.708460
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import infrastructure.database.types as qip

revision: str = "a3246f652ccf"
down_revision: str | None = "7b9c71f2609c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "volatility_surfaces",
        sa.Column("surface_id", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("underlying_id", sa.Uuid(), nullable=False),
        sa.Column("as_of_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("model", sa.String(length=24), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.Column("curve_id", sa.String(length=64), nullable=True),
        sa.Column("slices_total", sa.Integer(), nullable=False),
        sa.Column("slices_fitted", sa.Integer(), nullable=False),
        sa.Column("calibration_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("summary", qip.JSONDict(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("slices_fitted <= slices_total", name="ck_surface_fitted_le_total"),
        sa.ForeignKeyConstraint(["analysis_id"], ["chain_analyses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["underlying_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("volatility_surfaces", schema=None) as batch_op:
        batch_op.create_index(
            "ix_surfaces_underlying", ["underlying_id", "as_of_timestamp"], unique=False
        )
        batch_op.create_index("ix_surfaces_user", ["user_id", "created_at"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_volatility_surfaces_surface_id"), ["surface_id"], unique=False
        )

    op.create_table(
        "arbitrage_reports",
        sa.Column("surface_id", sa.Uuid(), nullable=True),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=24), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=True),
        sa.Column("violations_total", sa.Integer(), nullable=False),
        sa.Column("observations", sa.Integer(), nullable=False),
        sa.Column("checks_run", qip.JSONDict(), nullable=False),
        sa.Column("summary", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["analysis_id"], ["chain_analyses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["surface_id"], ["volatility_surfaces.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("surface_id", "scope", name="uq_arbitrage_report_scope"),
    )
    with op.batch_alter_table("arbitrage_reports", schema=None) as batch_op:
        batch_op.create_index(
            "ix_arbitrage_reports_analysis", ["analysis_id", "scope", "created_at"], unique=False
        )

    op.create_table(
        "surface_slices",
        sa.Column("surface_id", sa.Uuid(), nullable=False),
        sa.Column("expiry", sa.Date(), nullable=False),
        sa.Column("time_to_expiry", sa.Float(), nullable=False),
        sa.Column("forward", sa.Float(), nullable=False),
        sa.Column("discount_factor", sa.Float(), nullable=False),
        sa.Column("forward_method", sa.String(length=24), nullable=True),
        sa.Column("forward_confidence", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("n_observations", sa.Integer(), nullable=False),
        sa.Column("rmse_total_variance", sa.Float(), nullable=True),
        sa.Column("weighted_rmse", sa.Float(), nullable=True),
        sa.Column("rmse_vol_points", sa.Float(), nullable=True),
        sa.Column("max_error_vol_points", sa.Float(), nullable=True),
        sa.Column("optimizer", sa.String(length=24), nullable=False),
        sa.Column("optimizer_message", sa.String(length=255), nullable=True),
        sa.Column("iterations", sa.Integer(), nullable=False),
        sa.Column("starts_attempted", sa.Integer(), nullable=False),
        sa.Column("starts_feasible", sa.Integer(), nullable=False),
        sa.Column("min_durrleman_g", sa.Float(), nullable=True),
        sa.Column("min_durrleman_k", sa.Float(), nullable=True),
        sa.Column("wing_slope", sa.Float(), nullable=True),
        sa.Column("constraints_satisfied", sa.Boolean(), nullable=False),
        sa.Column("k_min", sa.Float(), nullable=True),
        sa.Column("k_max", sa.Float(), nullable=True),
        sa.Column("error", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["surface_id"], ["volatility_surfaces.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("surface_id", "expiry", name="uq_surface_slice_expiry"),
    )
    with op.batch_alter_table("surface_slices", schema=None) as batch_op:
        batch_op.create_index("ix_surface_slices_surface", ["surface_id", "expiry"], unique=False)

    op.create_table(
        "arbitrage_violations",
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("scope", sa.String(length=24), nullable=False),
        sa.Column("violation_type", sa.String(length=24), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("magnitude", sa.Float(), nullable=False),
        sa.Column("tolerance", sa.Float(), nullable=True),
        sa.Column("expiry", sa.Date(), nullable=True),
        sa.Column("strike", qip.DecimalType(), nullable=True),
        sa.Column("option_type", sa.String(length=8), nullable=True),
        sa.Column("detail", qip.JSONDict(), nullable=False),
        sa.Column("affected_instruments", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["report_id"], ["arbitrage_reports.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("arbitrage_violations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_arbitrage_violations_expiry", ["report_id", "expiry"], unique=False
        )
        batch_op.create_index(
            "ix_arbitrage_violations_report", ["report_id", "severity"], unique=False
        )

    op.create_table(
        "surface_parameters",
        sa.Column("slice_id", sa.Uuid(), nullable=False),
        sa.Column("parameterization", sa.String(length=24), nullable=False),
        sa.Column("a", sa.Float(), nullable=False),
        sa.Column("b", sa.Float(), nullable=False),
        sa.Column("rho", sa.Float(), nullable=False),
        sa.Column("m", sa.Float(), nullable=False),
        sa.Column("sigma", sa.Float(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["slice_id"], ["surface_slices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slice_id", "parameterization", name="uq_slice_parameterization"),
    )
    with op.batch_alter_table("option_implied_vols", schema=None) as batch_op:
        batch_op.add_column(sa.Column("price_spread", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("option_implied_vols", schema=None) as batch_op:
        batch_op.drop_column("price_spread")

    op.drop_table("surface_parameters")
    with op.batch_alter_table("arbitrage_violations", schema=None) as batch_op:
        batch_op.drop_index("ix_arbitrage_violations_report")
        batch_op.drop_index("ix_arbitrage_violations_expiry")

    op.drop_table("arbitrage_violations")
    with op.batch_alter_table("surface_slices", schema=None) as batch_op:
        batch_op.drop_index("ix_surface_slices_surface")

    op.drop_table("surface_slices")
    with op.batch_alter_table("arbitrage_reports", schema=None) as batch_op:
        batch_op.drop_index("ix_arbitrage_reports_analysis")

    op.drop_table("arbitrage_reports")
    with op.batch_alter_table("volatility_surfaces", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_volatility_surfaces_surface_id"))
        batch_op.drop_index("ix_surfaces_user")
        batch_op.drop_index("ix_surfaces_underlying")

    op.drop_table("volatility_surfaces")
    # ### end Alembic commands ###
