"""phase 3 anomaly analytics

Revision ID: c338aad70490
Revises: a3246f652ccf
Create Date: 2026-09-01 18:20:19.627580
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import infrastructure.database.types as qip

revision: str = "c338aad70490"
down_revision: str | None = "a3246f652ccf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "anomaly_scans",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("surface_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("underlying_id", sa.Uuid(), nullable=False),
        sa.Column("as_of_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("quotes_examined", sa.Integer(), nullable=False),
        sa.Column("quotes_scored", sa.Integer(), nullable=False),
        sa.Column("flagged", sa.Integer(), nullable=False),
        sa.Column("policy", qip.JSONDict(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("flagged <= quotes_scored", name="ck_scan_flagged_le_scored"),
        sa.ForeignKeyConstraint(["analysis_id"], ["chain_analyses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["surface_id"], ["volatility_surfaces.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("anomaly_scans", schema=None) as batch_op:
        batch_op.create_index(
            "ix_anomaly_scans_underlying", ["user_id", "underlying_id", "created_at"], unique=False
        )

    op.create_table(
        "surface_characteristics",
        sa.Column("surface_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("underlying_id", sa.Uuid(), nullable=False),
        sa.Column("as_of_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("tenor_days", sa.Integer(), nullable=False),
        sa.Column("time_to_expiry", sa.Float(), nullable=False),
        sa.Column("forward", sa.Float(), nullable=False),
        sa.Column("atm_volatility", sa.Float(), nullable=False),
        sa.Column("skew", sa.Float(), nullable=False),
        sa.Column("curvature", sa.Float(), nullable=False),
        sa.Column("atm_total_variance", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=32), nullable=False),
        sa.Column("flags", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["surface_id"], ["volatility_surfaces.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("surface_id", "tenor_days", name="uq_characteristic_tenor"),
    )
    with op.batch_alter_table("surface_characteristics", schema=None) as batch_op:
        batch_op.create_index(
            "ix_characteristics_history",
            ["user_id", "underlying_id", "tenor_days", "as_of_timestamp"],
            unique=False,
        )

    op.create_table(
        "surface_anomalies",
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("expiry", sa.Date(), nullable=False),
        sa.Column("strike", qip.DecimalType(), nullable=False),
        sa.Column("option_type", sa.String(length=8), nullable=False),
        sa.Column("market_iv", sa.Float(), nullable=False),
        sa.Column("reference_iv", sa.Float(), nullable=False),
        sa.Column("iv_difference", sa.Float(), nullable=False),
        sa.Column("relative_deviation", sa.Float(), nullable=False),
        sa.Column("market_iv_bid", sa.Float(), nullable=True),
        sa.Column("market_iv_ask", sa.Float(), nullable=True),
        sa.Column("envelope_position", sa.String(length=16), nullable=False),
        sa.Column("excess_over_envelope", sa.Float(), nullable=False),
        sa.Column("explained_scale", sa.Float(), nullable=False),
        sa.Column("z_score", sa.Float(), nullable=False),
        sa.Column("historical_z_score", sa.Float(), nullable=True),
        sa.Column("historical_observations", sa.Integer(), nullable=False),
        sa.Column("liquidity_score", sa.Float(), nullable=False),
        sa.Column("data_quality_score", sa.Float(), nullable=False),
        sa.Column("calibration_rmse_vol_points", sa.Float(), nullable=True),
        sa.Column("iv_uncertainty", sa.Float(), nullable=True),
        sa.Column("reference_method", sa.String(length=32), nullable=False),
        sa.Column("reference_flags", qip.JSONDict(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("flagged", sa.Boolean(), nullable=False),
        sa.Column("explanation", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "flagged = false OR confidence > 0", name="ck_flagged_anomaly_has_confidence"
        ),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["scan_id"], ["anomaly_scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("surface_anomalies", schema=None) as batch_op:
        batch_op.create_index(
            "ix_surface_anomalies_instrument", ["instrument_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_surface_anomalies_scan", ["scan_id", "flagged", "z_score"], unique=False
        )

    with op.batch_alter_table("option_implied_vols", schema=None) as batch_op:
        batch_op.add_column(sa.Column("data_quality_score", sa.Float(), nullable=False))
        batch_op.add_column(sa.Column("liquidity_score", sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("option_implied_vols", schema=None) as batch_op:
        batch_op.drop_column("liquidity_score")
        batch_op.drop_column("data_quality_score")

    with op.batch_alter_table("surface_anomalies", schema=None) as batch_op:
        batch_op.drop_index("ix_surface_anomalies_scan")
        batch_op.drop_index("ix_surface_anomalies_instrument")

    op.drop_table("surface_anomalies")
    with op.batch_alter_table("surface_characteristics", schema=None) as batch_op:
        batch_op.drop_index("ix_characteristics_history")

    op.drop_table("surface_characteristics")
    with op.batch_alter_table("anomaly_scans", schema=None) as batch_op:
        batch_op.drop_index("ix_anomaly_scans_underlying")

    op.drop_table("anomaly_scans")
    # ### end Alembic commands ###
