"""phase 8 execution simulation

Revision ID: cdfffe7a2ea3
Revises: 7fe8f4fa4533
Create Date: 2026-09-02 17:34:44.284373
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import infrastructure.database.types as qip

revision: str = "cdfffe7a2ea3"
down_revision: str | None = "7fe8f4fa4533"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "execution_simulations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("comparison_id", sa.Uuid(), nullable=False),
        sa.Column("counterfactual", sa.Boolean(), nullable=False),
        sa.Column("strategy", sa.String(length=64), nullable=False),
        sa.Column("impact_model", sa.String(length=64), nullable=False),
        sa.Column("impact_is_calibrated", sa.Boolean(), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("ordered_quantity", qip.DecimalType(), nullable=False),
        sa.Column("filled_quantity", qip.DecimalType(), nullable=False),
        sa.Column("completion_rate", sa.Float(), nullable=False),
        sa.Column("average_price", qip.DecimalType(), nullable=True),
        sa.Column("window_start", qip.UTCDateTime(), nullable=False),
        sa.Column("window_end", qip.UTCDateTime(), nullable=False),
        sa.Column("latency_seconds", sa.Float(), nullable=False),
        sa.Column("max_price_age_seconds", sa.Float(), nullable=False),
        sa.Column("modelled_impact_cost", qip.DecimalType(), nullable=False),
        sa.Column("modelled_spread_cost", qip.DecimalType(), nullable=False),
        sa.Column("primary_benchmark", sa.String(length=24), nullable=True),
        sa.Column("shortfall_currency", sa.Float(), nullable=True),
        sa.Column("shortfall_bps", sa.Float(), nullable=True),
        sa.Column("schedule", qip.JSONDict(), nullable=False),
        sa.Column("context", qip.JSONDict(), nullable=False),
        sa.Column("fills", qip.JSONDict(), nullable=False),
        sa.Column("unfilled", qip.JSONDict(), nullable=False),
        sa.Column("benchmarks", qip.JSONDict(), nullable=False),
        sa.Column("warnings", qip.JSONDict(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(primary_benchmark IS NULL) = (shortfall_currency IS NULL)",
            name="ck_simulation_shortfall_needs_benchmark",
        ),
        sa.CheckConstraint(
            "completion_rate >= 0 AND completion_rate <= 1",
            name="ck_simulation_completion_rate_is_a_rate",
        ),
        sa.CheckConstraint("counterfactual", name="ck_simulation_is_always_counterfactual"),
        sa.CheckConstraint(
            "filled_quantity >= 0 AND filled_quantity <= ordered_quantity",
            name="ck_simulation_filled_within_ordered",
        ),
        sa.CheckConstraint("ordered_quantity > 0", name="ck_simulation_ordered_quantity_positive"),
        sa.CheckConstraint("window_end >= window_start", name="ck_simulation_window_ordered"),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("execution_simulations", schema=None) as batch_op:
        batch_op.create_index("ix_simulations_comparison", ["comparison_id"], unique=False)
        batch_op.create_index("ix_simulations_user", ["user_id", "created_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("execution_simulations", schema=None) as batch_op:
        batch_op.drop_index("ix_simulations_user")
        batch_op.drop_index("ix_simulations_comparison")

    op.drop_table("execution_simulations")
    # ### end Alembic commands ###
