"""phase 0 baseline

Revision ID: ce949be630d8
Revises:
Create Date: 2026-09-01 15:52:43.625462
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import infrastructure.database.types as qip

revision: str = "ce949be630d8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_quality_reports",
        sa.Column("scope_type", sa.String(length=32), nullable=False),
        sa.Column("scope_id", sa.Uuid(), nullable=False),
        sa.Column("stale_score", sa.Float(), nullable=False),
        sa.Column("spread_score", sa.Float(), nullable=False),
        sa.Column("liquidity_score", sa.Float(), nullable=False),
        sa.Column("consistency_score", sa.Float(), nullable=False),
        sa.Column("completeness_score", sa.Float(), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("flag_counts", qip.JSONDict(), nullable=False),
        sa.Column("flags", qip.JSONDict(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("data_quality_reports", schema=None) as batch_op:
        batch_op.create_index("ix_quality_reports_scope", ["scope_type", "scope_id"], unique=False)

    op.create_table(
        "instruments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("canonical_key", sa.String(length=200), nullable=False),
        sa.Column("asset_class", sa.String(length=24), nullable=False),
        sa.Column("exchange", sa.String(length=32), nullable=False),
        sa.Column("venue", sa.String(length=32), nullable=True),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("underlying_id", sa.Uuid(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("multiplier", qip.DecimalType(), nullable=False),
        sa.Column("tick_size", qip.DecimalType(), nullable=False),
        sa.Column("lot_size", qip.DecimalType(), nullable=False),
        sa.Column("expiry", sa.Date(), nullable=True),
        sa.Column("strike", qip.DecimalType(), nullable=True),
        sa.Column("option_type", sa.String(length=8), nullable=True),
        sa.Column("exercise_style", sa.String(length=16), nullable=True),
        sa.Column("settlement_type", sa.String(length=16), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("metadata", qip.JSONDict(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["underlying_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("canonical_key"),
    )
    with op.batch_alter_table("instruments", schema=None) as batch_op:
        batch_op.create_index("ix_instruments_asset_class", ["asset_class"], unique=False)
        batch_op.create_index(
            "ix_instruments_chain",
            ["underlying_id", "expiry", "strike", "option_type"],
            unique=False,
        )
        batch_op.create_index("ix_instruments_symbol", ["exchange", "symbol"], unique=False)

    op.create_table(
        "model_versions",
        sa.Column("model_name", sa.String(length=64), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column("model_type", sa.String(length=32), nullable=False),
        sa.Column("parameters", qip.JSONDict(), nullable=False),
        sa.Column("training_period_start", sa.Date(), nullable=True),
        sa.Column("training_period_end", sa.Date(), nullable=True),
        sa.Column("calibration_timestamp", qip.UTCDateTime(), nullable=True),
        sa.Column("code_commit", sa.String(length=64), nullable=True),
        sa.Column("metrics", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_name", "version", name="uq_model_name_version"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("resource_type", sa.String(length=48), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("metadata", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index("ix_audit_user_time", ["user_id", "created_at"], unique=False)

    op.create_table(
        "instrument_aliases",
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("alias_symbol", sa.String(length=128), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "alias_symbol", name="uq_alias_source_symbol"),
    )
    with op.batch_alter_table("instrument_aliases", schema=None) as batch_op:
        batch_op.create_index("ix_alias_instrument", ["instrument_id"], unique=False)

    op.create_table(
        "jobs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("job_type", sa.String(length=48), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("progress", sa.Float(), nullable=False),
        sa.Column("started_at", qip.UTCDateTime(), nullable=True),
        sa.Column("completed_at", qip.UTCDateTime(), nullable=True),
        sa.Column("input_reference", qip.JSONDict(), nullable=False),
        sa.Column("result_reference", qip.JSONDict(), nullable=True),
        sa.Column("error", qip.JSONDict(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("progress >= 0.0 AND progress <= 1.0", name="ck_job_progress_range"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_jobs_user_status", ["user_id", "status", "created_at"], unique=False
        )

    op.create_table(
        "market_quotes",
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("exchange_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("receive_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("bid_price", qip.DecimalType(), nullable=True),
        sa.Column("bid_size", qip.DecimalType(), nullable=True),
        sa.Column("ask_price", qip.DecimalType(), nullable=True),
        sa.Column("ask_size", qip.DecimalType(), nullable=True),
        sa.Column("last_price", qip.DecimalType(), nullable=True),
        sa.Column("last_size", qip.DecimalType(), nullable=True),
        sa.Column("volume", qip.DecimalType(), nullable=True),
        sa.Column("open_interest", qip.DecimalType(), nullable=True),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("sequence_number", sa.BigInteger(), nullable=True),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("quality_flags", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("market_quotes", schema=None) as batch_op:
        batch_op.create_index(
            "ix_market_quotes_instrument_time",
            ["instrument_id", "exchange_timestamp"],
            unique=False,
        )

    op.create_table(
        "uploads",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("stored_key", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("error", qip.JSONDict(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stored_key"),
    )
    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.create_index("ix_uploads_user", ["user_id", "created_at"], unique=False)

    op.create_table(
        "option_chain_snapshots",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("underlying_id", sa.Uuid(), nullable=False),
        sa.Column("as_of_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("dataset_digest", sa.String(length=64), nullable=True),
        sa.Column("upload_id", sa.Uuid(), nullable=True),
        sa.Column("underlying_price", qip.DecimalType(), nullable=True),
        sa.Column("rows_input", sa.Integer(), nullable=False),
        sa.Column("rows_kept", sa.Integer(), nullable=False),
        sa.Column("rows_excluded", sa.Integer(), nullable=False),
        sa.Column("rows_rejected", sa.Integer(), nullable=False),
        sa.Column("quality_summary", qip.JSONDict(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rows_input = rows_kept + rows_excluded + rows_rejected",
            name="ck_chain_snapshot_row_conservation",
        ),
        sa.ForeignKeyConstraint(["underlying_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["upload_id"], ["uploads.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("option_chain_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_chain_snapshots_underlying", ["underlying_id", "as_of_timestamp"], unique=False
        )
        batch_op.create_index("ix_chain_snapshots_user", ["user_id", "created_at"], unique=False)

    op.create_table(
        "option_quotes",
        sa.Column("chain_snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("underlying_id", sa.Uuid(), nullable=False),
        sa.Column("source_row_number", sa.Integer(), nullable=True),
        sa.Column("expiry", sa.Date(), nullable=False),
        sa.Column("strike", qip.DecimalType(), nullable=False),
        sa.Column("option_type", sa.String(length=8), nullable=False),
        sa.Column("exchange_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("receive_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("bid_price", qip.DecimalType(), nullable=True),
        sa.Column("bid_size", qip.DecimalType(), nullable=True),
        sa.Column("ask_price", qip.DecimalType(), nullable=True),
        sa.Column("ask_size", qip.DecimalType(), nullable=True),
        sa.Column("last_price", qip.DecimalType(), nullable=True),
        sa.Column("volume", qip.DecimalType(), nullable=True),
        sa.Column("open_interest", qip.DecimalType(), nullable=True),
        sa.Column("sequence_number", sa.BigInteger(), nullable=True),
        sa.Column("underlying_price", qip.DecimalType(), nullable=True),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("stale_score", sa.Float(), nullable=False),
        sa.Column("spread_score", sa.Float(), nullable=False),
        sa.Column("liquidity_score", sa.Float(), nullable=False),
        sa.Column("consistency_score", sa.Float(), nullable=False),
        sa.Column("completeness_score", sa.Float(), nullable=False),
        sa.Column("quality_flags", qip.JSONDict(), nullable=False),
        sa.Column("excluded", sa.Boolean(), nullable=False),
        sa.Column("exclusion_reason", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "excluded = false OR exclusion_reason IS NOT NULL", name="ck_excluded_quote_has_reason"
        ),
        sa.ForeignKeyConstraint(
            ["chain_snapshot_id"], ["option_chain_snapshots.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("option_quotes", schema=None) as batch_op:
        batch_op.create_index(
            "ix_option_quotes_chain",
            ["chain_snapshot_id", "expiry", "strike", "option_type"],
            unique=False,
        )
        batch_op.create_index(
            "ix_option_quotes_instrument", ["instrument_id", "exchange_timestamp"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("option_quotes", schema=None) as batch_op:
        batch_op.drop_index("ix_option_quotes_instrument")
        batch_op.drop_index("ix_option_quotes_chain")

    op.drop_table("option_quotes")
    with op.batch_alter_table("option_chain_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_chain_snapshots_user")
        batch_op.drop_index("ix_chain_snapshots_underlying")

    op.drop_table("option_chain_snapshots")
    with op.batch_alter_table("uploads", schema=None) as batch_op:
        batch_op.drop_index("ix_uploads_user")

    op.drop_table("uploads")
    with op.batch_alter_table("market_quotes", schema=None) as batch_op:
        batch_op.drop_index("ix_market_quotes_instrument_time")

    op.drop_table("market_quotes")
    with op.batch_alter_table("jobs", schema=None) as batch_op:
        batch_op.drop_index("ix_jobs_user_status")

    op.drop_table("jobs")
    with op.batch_alter_table("instrument_aliases", schema=None) as batch_op:
        batch_op.drop_index("ix_alias_instrument")

    op.drop_table("instrument_aliases")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index("ix_audit_user_time")

    op.drop_table("audit_logs")
    op.drop_table("users")
    op.drop_table("model_versions")
    with op.batch_alter_table("instruments", schema=None) as batch_op:
        batch_op.drop_index("ix_instruments_symbol")
        batch_op.drop_index("ix_instruments_chain")
        batch_op.drop_index("ix_instruments_asset_class")

    op.drop_table("instruments")
    with op.batch_alter_table("data_quality_reports", schema=None) as batch_op:
        batch_op.drop_index("ix_quality_reports_scope")

    op.drop_table("data_quality_reports")
    # ### end Alembic commands ###
