"""phase 5 risk

Revision ID: df6172d6f160
Revises: fe9cbeb0f691
Create Date: 2026-09-02 15:16:20.750506
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import infrastructure.database.types as qip

revision: str = "df6172d6f160"
down_revision: str | None = "fe9cbeb0f691"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stress_scenarios",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("shocks", qip.JSONDict(), nullable=False),
        sa.Column("derivation", qip.JSONDict(), nullable=True),
        sa.Column("scenario_metadata", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source <> 'DERIVED_FROM_HISTORY' OR derivation IS NOT NULL",
            name="ck_scenario_historical_claim_has_derivation",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stress_scenarios", schema=None) as batch_op:
        batch_op.create_index("ix_scenarios_user", ["user_id", "created_at"], unique=False)
        batch_op.create_index("ix_scenarios_user_name", ["user_id", "name"], unique=True)

    op.create_table(
        "risk_snapshots",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("valuation_id", sa.Uuid(), nullable=False),
        sa.Column("as_of_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("market_state_id", sa.String(length=64), nullable=True),
        sa.Column("positions", sa.Integer(), nullable=False),
        sa.Column("excluded_positions", sa.Integer(), nullable=False),
        sa.Column("base_value", sa.Float(), nullable=False),
        sa.Column("reported_value", sa.Float(), nullable=False),
        sa.Column("delta", sa.Float(), nullable=False),
        sa.Column("gamma", sa.Float(), nullable=False),
        sa.Column("vega_per_vol_point", sa.Float(), nullable=False),
        sa.Column("theta_per_day", sa.Float(), nullable=False),
        sa.Column("rho_per_bp", sa.Float(), nullable=False),
        sa.Column("excluded", qip.JSONDict(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "excluded_positions >= 0", name="ck_risk_snapshot_excluded_non_negative"
        ),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["valuation_id"], ["portfolio_valuations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("risk_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_risk_snapshots_portfolio", ["portfolio_id", "as_of_timestamp"], unique=False
        )

    op.create_table(
        "stress_results",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("scenario_id", sa.Uuid(), nullable=True),
        sa.Column("scenario_name", sa.String(length=120), nullable=False),
        sa.Column("scenario_source", sa.String(length=32), nullable=False),
        sa.Column("shocks", qip.JSONDict(), nullable=False),
        sa.Column("base_value", sa.Float(), nullable=False),
        sa.Column("shocked_value", sa.Float(), nullable=False),
        sa.Column("pnl", sa.Float(), nullable=False),
        sa.Column("greek_estimate", sa.Float(), nullable=False),
        sa.Column("time_decay_days", sa.Float(), nullable=False),
        sa.Column("floored_volatilities", sa.Integer(), nullable=False),
        sa.Column("contributions", qip.JSONDict(), nullable=False),
        sa.Column("positions", qip.JSONDict(), nullable=False),
        sa.Column("warnings", qip.JSONDict(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scenario_id"], ["stress_scenarios.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["risk_snapshots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stress_results", schema=None) as batch_op:
        batch_op.create_index(
            "ix_stress_results_portfolio", ["portfolio_id", "created_at"], unique=False
        )
        batch_op.create_index("ix_stress_results_snapshot", ["snapshot_id"], unique=False)

    op.create_table(
        "var_results",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("method", sa.String(length=24), nullable=False),
        sa.Column("horizon_days", sa.Integer(), nullable=False),
        sa.Column("scenarios", sa.Integer(), nullable=False),
        sa.Column("base_value", sa.Float(), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=True),
        sa.Column("tail_risk", qip.JSONDict(), nullable=False),
        sa.Column("estimate_intervals", qip.JSONDict(), nullable=False),
        sa.Column("assumptions", qip.JSONDict(), nullable=False),
        sa.Column("factor_panel", qip.JSONDict(), nullable=False),
        sa.Column("warnings", qip.JSONDict(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "method <> 'MONTE_CARLO' OR seed IS NOT NULL",
            name="ck_var_monte_carlo_records_its_seed",
        ),
        sa.CheckConstraint("scenarios >= 0", name="ck_var_scenarios_non_negative"),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["risk_snapshots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("var_results", schema=None) as batch_op:
        batch_op.create_index(
            "ix_var_results_portfolio", ["portfolio_id", "created_at"], unique=False
        )
        batch_op.create_index("ix_var_results_snapshot", ["snapshot_id", "method"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("var_results", schema=None) as batch_op:
        batch_op.drop_index("ix_var_results_snapshot")
        batch_op.drop_index("ix_var_results_portfolio")

    op.drop_table("var_results")
    with op.batch_alter_table("stress_results", schema=None) as batch_op:
        batch_op.drop_index("ix_stress_results_snapshot")
        batch_op.drop_index("ix_stress_results_portfolio")

    op.drop_table("stress_results")
    with op.batch_alter_table("risk_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_risk_snapshots_portfolio")

    op.drop_table("risk_snapshots")
    with op.batch_alter_table("stress_scenarios", schema=None) as batch_op:
        batch_op.drop_index("ix_scenarios_user_name")
        batch_op.drop_index("ix_scenarios_user")

    op.drop_table("stress_scenarios")
    # ### end Alembic commands ###
