"""phase 4 portfolio

Revision ID: fe9cbeb0f691
Revises: c338aad70490
Create Date: 2026-09-02 12:28:32.601319
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import infrastructure.database.types as qip

revision: str = "fe9cbeb0f691"
down_revision: str | None = "c338aad70490"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "portfolios",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("portfolios", schema=None) as batch_op:
        batch_op.create_index("ix_portfolios_user", ["user_id", "created_at"], unique=False)

    op.create_table(
        "portfolio_valuations",
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("as_of_timestamp", qip.UTCDateTime(), nullable=False),
        sa.Column("base_currency", sa.String(length=3), nullable=False),
        sa.Column("market_state_id", sa.String(length=64), nullable=True),
        sa.Column("positions", sa.Integer(), nullable=False),
        sa.Column("valued", sa.Integer(), nullable=False),
        sa.Column("base_market_value", qip.DecimalType(), nullable=False),
        sa.Column("unrealized_pnl", qip.DecimalType(), nullable=False),
        sa.Column("gross_exposure", qip.DecimalType(), nullable=False),
        sa.Column("net_exposure", qip.DecimalType(), nullable=False),
        sa.Column("delta", sa.Float(), nullable=False),
        sa.Column("gamma", sa.Float(), nullable=False),
        sa.Column("vega_per_vol_point", sa.Float(), nullable=False),
        sa.Column("theta_per_day", sa.Float(), nullable=False),
        sa.Column("rho_per_bp", sa.Float(), nullable=False),
        sa.Column("valuation_methods", qip.JSONDict(), nullable=False),
        sa.Column("aggregates", qip.JSONDict(), nullable=False),
        sa.Column("provenance", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("valued <= positions", name="ck_valuation_valued_le_positions"),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("portfolio_valuations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_portfolio_valuations", ["portfolio_id", "as_of_timestamp"], unique=False
        )

    op.create_table(
        "positions",
        sa.Column("portfolio_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", qip.DecimalType(), nullable=False),
        sa.Column("side", sa.String(length=8), nullable=False),
        sa.Column("average_price", qip.DecimalType(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("strategy_tag", sa.String(length=64), nullable=True),
        sa.Column("metadata", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity <> 0", name="ck_position_quantity_non_zero"),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["portfolio_id"], ["portfolios.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_positions_portfolio", ["portfolio_id", "instrument_id"], unique=False
        )

    op.create_table(
        "position_valuations",
        sa.Column("valuation_id", sa.Uuid(), nullable=False),
        sa.Column("position_id", sa.Uuid(), nullable=False),
        sa.Column("instrument_id", sa.Uuid(), nullable=False),
        sa.Column("canonical_key", sa.String(length=200), nullable=False),
        sa.Column("asset_class", sa.String(length=24), nullable=False),
        sa.Column("underlying_id", sa.Uuid(), nullable=True),
        sa.Column("expiry", sa.Date(), nullable=True),
        sa.Column("strike", qip.DecimalType(), nullable=True),
        sa.Column("option_type", sa.String(length=8), nullable=True),
        sa.Column("quantity", qip.DecimalType(), nullable=False),
        sa.Column("multiplier", qip.DecimalType(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("market_price", qip.DecimalType(), nullable=True),
        sa.Column("model_price", qip.DecimalType(), nullable=True),
        sa.Column("price_used", qip.DecimalType(), nullable=True),
        sa.Column("valuation_method", sa.String(length=24), nullable=False),
        sa.Column("market_value", qip.DecimalType(), nullable=True),
        sa.Column("base_market_value", qip.DecimalType(), nullable=True),
        sa.Column("fx_rate", qip.DecimalType(), nullable=True),
        sa.Column("unrealized_pnl", qip.DecimalType(), nullable=True),
        sa.Column("delta", sa.Float(), nullable=False),
        sa.Column("gamma", sa.Float(), nullable=False),
        sa.Column("vega_per_vol_point", sa.Float(), nullable=False),
        sa.Column("theta_per_day", sa.Float(), nullable=False),
        sa.Column("rho_per_bp", sa.Float(), nullable=False),
        sa.Column("greek_source", sa.String(length=24), nullable=False),
        sa.Column("implied_volatility", sa.Float(), nullable=True),
        sa.Column("time_to_expiry", sa.Float(), nullable=True),
        sa.Column("quote_age_seconds", sa.Float(), nullable=True),
        sa.Column("warnings", qip.JSONDict(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            qip.UTCDateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "base_market_value IS NOT NULL OR valuation_method = 'UNAVAILABLE'",
            name="ck_position_valuation_has_value_or_reason",
        ),
        sa.ForeignKeyConstraint(["instrument_id"], ["instruments.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["valuation_id"], ["portfolio_valuations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("position_valuations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_position_valuations", ["valuation_id", "asset_class"], unique=False
        )
        batch_op.create_index("ix_position_valuations_instrument", ["instrument_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("position_valuations", schema=None) as batch_op:
        batch_op.drop_index("ix_position_valuations_instrument")
        batch_op.drop_index("ix_position_valuations")

    op.drop_table("position_valuations")
    with op.batch_alter_table("positions", schema=None) as batch_op:
        batch_op.drop_index("ix_positions_portfolio")

    op.drop_table("positions")
    with op.batch_alter_table("portfolio_valuations", schema=None) as batch_op:
        batch_op.drop_index("ix_portfolio_valuations")

    op.drop_table("portfolio_valuations")
    with op.batch_alter_table("portfolios", schema=None) as batch_op:
        batch_op.drop_index("ix_portfolios_user")

    op.drop_table("portfolios")
    # ### end Alembic commands ###
